import type { Metadata } from "next";
import "./globals.css";
import Footer from "./MyComponents/Footer";
import { Figtree } from "next/font/google";

const figtree = Figtree({
  subsets: ["latin"],
  variable: "--font-figtree",
  display: "swap",
});

export const metadata: Metadata = {
  title: "My Portfolio - AL",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={figtree.variable}>
      <body className="font-sans">
        <div className={`${figtree.variable} font-main`}>
          {children}

          <div className="flex justify-center bg-black pt-20 ">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
